### ISSUE TITLE
Fails to compile

### ISSUE THREAD

**Issue by Barbaross93** [liquid600pgm/pomod#1]
Hi @liquidev! Thanks for sharing this project! It's quite literally the best script I've found for a polybar pomodoro indicator.  However, I was trying to make a few adjustments to suit my needs and tried to compile it with `nimble install` in the `pomod` directory.  I get the following output:
```
Verifying dependencies for pomod@0.1.0
    Prompt: No local packages.json found, download it from internet? [y/N]
    Answer: y
Downloading Official package list
    Success Package list downloaded.
 Installing dbus@any version
Downloading https://github.com/zielmicha/nim-dbus using git
  Verifying dependencies for dbus@0.0.1
 Installing dbus@0.0.1
   Success: dbus installed successfully.
 Installing rapid@any version
Downloading https://github.com/liquid600pgm/rapid using git
  Verifying dependencies for rapid@0.1.0
 Installing glm@>= 1.1.1
Downloading https://github.com/stavenko/nim-glm using git
  Verifying dependencies for glm@1.1.1
 Installing glm@1.1.1
   Success: glm installed successfully.
 Installing nimterop@any version
Downloading https://github.com/genotrance/nimterop using git
  Verifying dependencies for nimterop@0.6.13
 Installing regex@>= 0.15.0
Downloading https://github.com/nitely/nim-regex using git
  Verifying dependencies for regex@0.19.0
 Installing unicodedb@>= 0.7.2
Downloading https://github.com/nitely/nim-unicodedb using git
  Verifying dependencies for unicodedb@0.9.0
 Installing unicodedb@0.9.0
   Success: unicodedb installed successfully.
 Installing regex@0.19.0
   Success: regex installed successfully.
 Installing cligen@>= 1.0.0
Downloading https://github.com/c-blake/cligen.git using git
  Verifying dependencies for cligen@1.5.0
 Installing cligen@1.5.0
   Success: cligen installed successfully.
 Installing nimterop@0.6.13
   Building nimterop/nimterop/loaf using c backend
   Building nimterop/nimterop/toast using c backend
# Resetting /home/barbarossa/.cache/nim/nimterop/nimterop/treesitter
# Resetting /home/barbarossa/.cache/nim/nimterop/nimterop/treesitter_c
# Resetting /home/barbarossa/.cache/nim/nimterop/nimterop/treesitter_cpp
   Success: nimterop installed successfully.
 Installing nimPNG@any version
Downloading https://github.com/jangko/nimPNG using git
  Verifying dependencies for nimPNG@0.3.1
 Installing nimPNG@0.3.1
   Success: nimPNG installed successfully.
 Installing rapid@0.1.0
   Success: rapid installed successfully.
 Installing pomod@0.1.0
   Building pomod/pomod using c backend
/home/barbarossa/.nimble/pkgs/rapid-0.1.0/rapid/lib/soundio.nim(13, 16) Error: cannot open file: nimterop/git
       Tip: 273 messages have been suppressed, use --verbose to show them.
     Error: Build failed for package: pomod
        ... Execution failed with exit code 1
        ... Command: /usr/bin/nim c --colors:on --noNimblePath -d:release -d:NimblePkgVersion=0.1.0 --path:/home/barbarossa/.nimble/pkgs/dbus-0.0.1 --path:/home/barbarossa/.nimble/pkgs/glm-1.1.1 --path:/home/barbarossa/.nimble/pkgs/unicodedb-0.9.0 --path:/home/barbarossa/.nimble/pkgs/regex-0.19.0 --path:/home/barbarossa/.nimble/pkgs/cligen-1.5.0 --path:/home/barbarossa/.nimble/pkgs/nimterop-0.6.13 --path:/home/barbarossa/.nimble/pkgs/nimPNG-0.3.1 --path:/home/barbarossa/.nimble/pkgs/rapid-0.1.0 --hints:off -o:/home/barbarossa/pomod/pomod /home/barbarossa/pomod/src/pomod.nim
```
It looks like there's a problem with `niterop/git` but I have no idea how to remedy this. Do you have any tips for fixing this?

**Comment by liquidev** [comment]
Well, I think the only quick solution right now would be to get rid of the audio component of pomod. Back when I made this I didn't really have anything better than my own game engine for audio (and I still don't), but that old version of the game engine had a lot of compilation problems on people's machines that I ultimately didn't know how to resolve. The best I can do right now is to remove the sound effect. The module will still send you a freedesktop notification via dbus, so if you have a notification OSD (like dunst) set up, you'll see when a pomodoro/break is over, just not hear it.

**Comment by Barbaross93** [comment]
That's perfectly fine with me! What parts of the code do I need to cut out?

**Comment by liquidev** [comment]
Alright, so there's a couple of things. First, remove the imports:

https://github.com/liquidev/pomod/blob/578a0099e502641c7222ea5300e93428175d5bd7/src/pomod.nim#L135-L136

Next, remove the audio init code:

https://github.com/liquidev/pomod/blob/578a0099e502641c7222ea5300e93428175d5bd7/src/pomod.nim#L173-L177

and remove the sound playback code:

https://github.com/liquidev/pomod/blob/578a0099e502641c7222ea5300e93428175d5bd7/src/pomod.nim#L189-L191

That should be everything as far as I remember. Let me know if you run into any other compile errors, AFAIK the rest of the script doesn't use my game engine so you should be fine.

**Comment by Barbaross93** [comment]
Perfect, that works! Thank you! Quick question though, is it possible to go to the next state? i.e., from work period to break? Looks like there is a nextState function, is there a way to call it? Unfortunately it seems that there's only two SIGUSR signals so I 'm not sure how else to call it. I'll close this for now since my issue is technically solved.

**Comment by liquidev** [comment]
I didn't expose any way to call `nextState`, no. If you want a nice exercise I suppose you could play around with FIFOs to create a better IPC scheme, or just reuse one of the existing signals. Although do keep in mind that I picked SIGUSR{1,2} because they were the only two user-defined signals without any implied meaning, unless there's a SIGUSR3 I'm not aware of.

**Comment by Barbaross93** [comment]
Actually, I just changed the reset signal to SIGHUP (which I think pomod would reset regardless of actually using the reset function) and use SIGUSR2 to toggle to the next state. Works flawlessly. Thanks so much!
